[package]
name = "hyprland-display-switcher"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
hyprland = "0.4.0-beta.2"
iced = "0.13.1"
serde = "1.0.219"
serde_json = "1.0.143"
tokio = "1.47.1"
